### ISSUE TITLE
Commas in slugs/cuids on React Native IOS

### ISSUE THREAD

**Issue by potatopotaro** [paralleldrive/cuid#147]
Environment: React-Native, iOS, cuid npm version 2.1.6

All of my slugs/cuids have a comma character in the middle, e.g. cuid() returns "cjv2di9mh0000,AWSaoa02jd8", cuid.slug() returns "mi1,Si0"

Is this supposed to be the case?

**Comment by potatopotaro** [comment]
Note, this goes all the way back to cuid@2.0.2, as far as I can tell.

**Comment by ericelliott** [comment]
No, it definitely should not be happening.

**Comment by uxname** [comment]
In android too

**Comment by ericelliott** [comment]
Open to a PR. I don't use those platforms. If this is important to your business, please feel free to [post and advertise a bounty](https://www.bountysource.com/) to get it fixed.

**Comment by ericelliott** [comment]
Please reopen if this is still an issue.
