### ISSUE TITLE
Nativescript builds report as node, but don't have a `global.process`

### ISSUE THREAD

**Issue by bensleveritt** [paralleldrive/cuid#169]
Presumably similar to React Native, Nativescript might need to be treated differently to browsers and Node, given that it doesn't have a `global.process`. I'm not familiar with the details of Nativescript but I'd hope it's a little like React Native.

**Comment by ericelliott** [comment]
Fixed in [Cuid2](https://github.com/paralleldrive/cuid2). Cuid2 does not depend on `global.process`.
