### ISSUE TITLE
I made a cli wrapper called `cuid-cli`

### ISSUE THREAD

**Issue by CanRau** [paralleldrive/cuid#171]
I made this actually long time ago, yet as the friendly @schickling just gave me access to his [`cuid-cli`](https://www.npmjs.com/package/cuid-cli) package and I could merge my scoped CLI, I thought it might interest people to know that it exists.

I use it to quickly generate 1 or more cuids when I'm manually adding a new entry to a db e.g. for debugging purposes or writing a markdown blog still without generator/cms.

Maybe it could be added to the readme, just didn't know where to put it as I think it's not a port.

By the way, it's not at all urgent, just a little fyi :wink:

**Comment by ericelliott** [comment]
Open to a PR to add this to the readme.
