### ISSUE TITLE
Fails to work with cloudflare workers js runtime.

### ISSUE THREAD

**Issue by GauravRajSharma** [paralleldrive/cuid#241]
```js
var mimeTypesLength = navigator.mimeTypes ? navigator.mimeTypes.length : 0; // exact line where error occurs

// ReferenceError: navigator is not defined 
```
ReferenceError while using cuid package within cloudflare workers. From my understanding, for the node version, it generates the fingerprint from `process.pid` but it is failing on me.

**Comment by fergusmeiklejohn** [comment]
Is there a way we can use the browser implementation in JS isolates?

**Comment by hadri3n** [comment]
Hello! Did anyone succeed to make it run with Cloudflare Workers ?

**Comment by ericelliott** [comment]
I have a new implementation of cuid coming soon that will work in this context.

**Comment by ericelliott** [comment]
Fixed in [Cuid2](https://github.com/paralleldrive/cuid2).
