### ISSUE TITLE
Question: could we register a cuid: URI scheme, or URN scheme?

### ISSUE THREAD

**Issue by melvincarvalho** [paralleldrive/cuid#242]
## Question

Might it be useful to register cuids to give them one higher level of scope at web scale?

## Examples

It could look like

`cuid:ckxls1y3900009yrx442e23rf`

Or

`urn:cuid:ckxls1y3900009yrx442e23rf`

This doesnt handle slugs but would work for a full cuid

## Similar Use

This would be similar to:

https://en.wikipedia.org/wiki/Universally_unique_identifier#Format

Which has

`urn:uuid:123e4567-e89b-12d3-a456-426655440000`

## Benefits and Motivation

This has the benefit of being able to be put in a database full of different items identified in different ways, and able to tell what is what

Before registration, simply coming to a consensus of what it would look like would probably be enough to get implementations going

Motivation: I'd like to start using cuids together with [linked objects](https://linkedobjects.org/) where using a global URI is encouraged

**Comment by ericelliott** [comment]
I'd be happy to support this process, but I don't have time to champion a scheme standard for it.

**Comment by ericelliott** [comment]
The original Cuid specification is now deprecated in favor of [Cuid2](https://github.com/paralleldrive/cuid2).
