### ISSUE TITLE
Question: Is there an active Java implementation?

### ISSUE THREAD

**Issue by jmaister** [paralleldrive/cuid#245]
I would like to use cuid in a Java project. I've seen there is a link to a project, however, it is archived.

Is there any active Java implementation?

If not, I could implement it and keep it updated.

**Comment by ericelliott** [comment]
If it's not linked, I'm not aware of it.

**Comment by thibaultmeyer** [comment]
Hello @ericelliott @jmaister,

I've uploaded my Java implementation of the CUID compatible with Java 8 and above. You can find it in this repos: https://github.com/thibaultmeyer/cuid-java.

It would be interesting to create an organization to gather all the implementations in the same place as well as the source of the web site. "usecuid" is available, could be a good name for the organization. What do you think about this idea?

**Comment by ericelliott** [comment]
Open a PR and reference this issue number, and I'll merge into the list of CUID ports.

Organizations cost money to maintain (GitHub Free is missing crucial features like protected branches), so unless we get funding, I'm not going to create an org unless somebody wants to guarantee funding.

**Comment by thibaultmeyer** [comment]
OK I will open a PR to reference this new java implementation. 

Why do you need to protect the branches? The use of roles defining the people allowed to write/read/only manage PR/... on the repository works very well (like many open source projects that don't want to pay github).

**Comment by ericelliott** [comment]
Merged.
