### ISSUE TITLE
Usage of new Date().getTime() vs Date.now

### ISSUE THREAD

**Issue by Compositr** [paralleldrive/cuid#267]
On line [42](https://github.com/paralleldrive/cuid/blob/master/index.js#L42) the timestamp generated by creating a new `Date` instance and calling the `getTime` method on it. 

However, as shown by [this](https://jsben.ch/hBggP) benchmark, `Date.now` is ~15% faster than creating a new `Date` instance. Is there any specific reason to not use Date.now?

**Comment by ericelliott** [comment]
`Date.now()` was added to the ECMAScript spec in ES5. The original CUID implementation predates ES5's widespread availability by 2-3 years.

The slow path takes 100 - 120ms to calculate 1 million dates. The fast path takes 90 - 110ms. This is a tiny micro-optimization. You'd need to be generating hundreds of thousands of CUIDs in a tight loop (like a render loop) for this to make any notable impact with users. Is this actually a bottleneck for you, and if so, in what situation?
