### ISSUE TITLE
Check character

### ISSUE THREAD

**Issue by Fakepng** [paralleldrive/cuid#275]
Suggestion: Create a function that calculates a hash(or something that isn't long) of the cuid and concat it to the end of cuid. So function isCuid can check that the cuid has not been tampered with.

**Comment by ericelliott** [comment]
This is not going to happen in this library because it is not required in most apps that only need unique ids, but you could create your function that appends a checksum to the end of cuids, and then use that function anywhere you need a cuid in your own code.
