### ISSUE TITLE
cuid npm package does not mention the deprecated state

### ISSUE THREAD

**Issue by Jolg42** [paralleldrive/cuid#277]
@ericelliott Random thing I noticed when I was looking into cuid and cuid2 from https://github.com/prisma/prisma/issues/17102

The cuid package https://www.npmjs.com/package/cuid still displays the "old" README without the following warning
```
## Status: Deprecated due to security. Use [Cuid2](https://github.com/paralleldrive/cuid2), instead.

> Note: All monotonically increasing (auto-increment), and timestamp-based ids share the security issues with Cuid. V4 UUIDs and GUIDs are also insecure because it's possible to predict future values of many random algorithms, and many of them are biased, leading to increased probability of collision.
```

You could use `npm deprecate` for this https://docs.npmjs.com/cli/v9/commands/npm-deprecate maybe if you want to make the deprecation visible. Note that it's possible to deprecate all versions or only a specific version and the deprecation can be removed later if needed.

**Comment by ericelliott** [comment]
Fixed
